spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/healthcare
        username: healthcare_user
        password: healthcare_pass
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
        show-sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    jackson:
        serialization:
            write-dates-as-timestamps: false
    ai:
      openai:
          api-key: ${OPENAI_API_KEY:}
          chat:
             options:
               model: gpt-3.5-turbo
               temperature: 0.1

server:
    port: 8080
    address: 0.0.0.0

logging:
    level:
        com.healthcare: DEBUG
        org.hibernate.SQL: DEBUG

# AI Configuration
app:
    ai:
        openai:
            enabled: true
            api-key: ${OPENAI_API_KEY:}
            api-url: https://api.openai.com/v1/chat/completions
            model: gpt-3.5-turbo
        local:
            enabled: true


management:
    endpoints:
        web:
            exposure:
                include: health,info
    endpoint:
        health:
            show-details: always